### PR TITLE
Add proxy

### PR DESCRIPTION
**Pull request by Rudolph-Miller**

### CODE REVIEW

**Comment by sakama** [comment]
I'm working to add unit test for this PR.
Please wait for merge.

**Comment by civitaspo** [comment]
Ok, I'm waiting for you

**Comment by Rudolph-Miller** [comment]
@sakama

Thank your! :)

**Comment by civitaspo** [comment]
After the p-r is merged, I bump up this plugin to v0.0.4.

**Comment by civitaspo** [comment]
implemented by https://github.com/civitaspo/embulk-output-sftp/pull/11

**Comment by Rudolph-Miller** [comment]
@sakama 
Good job! :)

**Comment by sakama** [comment]
@Rudolph-Miller thanks!

**Pull request closed without merging**
